"""Gold stage — load Silver parquet files into Postgres + create indexes.

Tables loaded:
  - case, phenotype_event          (from cases.parquet, phenotype_events.parquet)
  - disease, disease_hpo, disease_gene
  - id_mapping
  - hpo_term, hpo_synonym
"""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Any

import pandas as pd
from sqlalchemy import text

from diageno.config import settings
from diageno.db.session import engine, SessionLocal
from diageno.db.models import Base
from diageno.etl.utils import read_parquet

logger = logging.getLogger("diageno.etl.gold")


def _init_schema() -> None:
    """Create all tables + extensions if they don't exist."""
    with engine.begin() as conn:
        conn.execute(text("CREATE EXTENSION IF NOT EXISTS \"uuid-ossp\""))
        conn.execute(text("CREATE EXTENSION IF NOT EXISTS \"vector\""))
    Base.metadata.create_all(engine)
    logger.info("Schema initialized (all tables created)")


def _upsert_df(
    df: pd.DataFrame,
    table_name: str,
    *,
    if_exists: str = "append",
    dtype: dict[str, Any] | None = None,
) -> int:
    """Load a DataFrame into a Postgres table. Returns number of rows."""
    if df.empty:
        logger.info("Skipping empty DataFrame for table '%s'", table_name)
        return 0
    # Truncate first to make idempotent
    with engine.begin() as conn:
        conn.execute(text(f'TRUNCATE TABLE "{table_name}" CASCADE'))
    df.to_sql(table_name, engine, if_exists=if_exists, index=False, method="multi", dtype=dtype)
    logger.info("Loaded %d rows → %s", len(df), table_name)
    return len(df)


def load_hpo_terms(silver: Path) -> None:
    """Load hpo_term + hpo_synonym."""
    terms_path = silver / "hpo_terms.parquet"
    syns_path = silver / "hpo_synonyms.parquet"

    if terms_path.exists():
        df = read_parquet(terms_path)
        _upsert_df(df, "hpo_term")
    if syns_path.exists():
        df = read_parquet(syns_path)
        _upsert_df(df, "hpo_synonym")


def load_diseases(silver: Path) -> None:
    """Load disease + disease_hpo + disease_gene."""
    for fname, table in [
        ("diseases.parquet", "disease"),
        ("disease_hpo.parquet", "disease_hpo"),
        ("disease_gene.parquet", "disease_gene"),
    ]:
        fpath = silver / fname
        if fpath.exists():
            df = read_parquet(fpath)
            _upsert_df(df, table)


def load_id_mapping(silver: Path) -> None:
    """Load id_mapping."""
    fpath = silver / "id_mapping.parquet"
    if fpath.exists():
        df = read_parquet(fpath)
        # Drop auto-increment id column if present, let DB generate
        if "id" in df.columns:
            df = df.drop(columns=["id"])
        _upsert_df(df, "id_mapping")


def load_cases(silver: Path) -> None:
    """Load case + phenotype_event from phenopacket-derived parquets."""
    cases_path = silver / "cases.parquet"
    pheno_path = silver / "phenotype_events.parquet"

    if cases_path.exists():
        df = read_parquet(cases_path)
        # case_id as string (will be stored as external_id; UUID generated by DB)
        if "case_id" in df.columns:
            df = df.rename(columns={"case_id": "external_id"})
        # Drop raw_json if too large for bulk insert
        _upsert_df(df, "case")

    if pheno_path.exists():
        df = read_parquet(pheno_path)
        if "case_id" in df.columns:
            # Map string case_id → UUID from loaded cases
            # For simplicity, store as external reference
            df = df.rename(columns={"case_id": "external_case_id"})
            logger.info(
                "Note: phenotype_events reference external_case_id; "
                "join to case.external_id for FK resolution."
            )
        # Skip direct load (needs FK resolution), store as staging
        staging_path = silver / "phenotype_events_staged.parquet"
        df.to_parquet(staging_path, index=False)
        logger.info("Staged phenotype events at %s (needs FK resolution)", staging_path)


def create_pgvector_indexes() -> None:
    """Create HNSW indexes on embedding tables if they exist."""
    with engine.begin() as conn:
        for idx, table, col in [
            ("ix_case_emb_hnsw", "case_embedding", "embedding"),
            ("ix_disease_emb_hnsw", "disease_embedding", "embedding"),
        ]:
            try:
                conn.execute(
                    text(
                        f"CREATE INDEX IF NOT EXISTS {idx} "
                        f'ON {table} USING hnsw ({col} vector_cosine_ops)'
                    )
                )
                logger.info("Created HNSW index %s", idx)
            except Exception as e:
                logger.warning("Could not create index %s: %s", idx, e)


def run() -> None:
    """Execute the full gold loading pipeline."""
    silver = settings.silver_dir

    logger.info("=== Gold: loading silver → Postgres ===")

    _init_schema()
    load_hpo_terms(silver)
    load_diseases(silver)
    load_id_mapping(silver)
    load_cases(silver)
    create_pgvector_indexes()

    logger.info("=== Gold loading complete ===")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO)
    run()
